name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install requirements.txt
        run: |
          pip3 install -r requirements.txt
      - name: Run test.py
        run: |
          python3 test.py --token=${{ secrets.TOKEN }}
