name: Push Event Tests

on: [push]

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, arm64] 
    steps:
      - name: Echo runner name
        run: |
          echo "Hello, runner: ${{ github.ref_name }}"
      - name: jq
        run: |
          touch jq.yaml
          curl 'https://api.github.com/repos/jqlang/jq/commits?per_page=5' | jq '.[0]'
      - name: npm
        run: |
          npm help
      - name: yarn
        run: |
          yarn help
      - name: pip
        run: |
          pip3 list
      - name: shellcheck
        run: |
          shellcheck
      - name: wget
        run: |
          wget --help
      - name: docker
        run: |
          docker ps
      - name: yq # fails since the binary downloaded is amd64
        run: |
          touch yq.yaml
          yq -i '.a.b[0].c = "cool"' yq.yaml
          cat yq.yaml
