name: Push Event Tests

on: [push]

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, arm64] 
    steps:
      - name: Echo runner name
        run: |
          echo "Hello, runner: ${{ github.ref_name }}"
      - name: yq
        run: |
          touch yq.yaml
          yq -i '.a.b[0].c = "cool"' yq.yaml
          cat yq.yaml
      - name: jq
        run: |
          touch jq.yaml
          curl 'https://api.github.com/repos/jqlang/jq/commits?per_page=5' | jq '.[0]'
