name: Tmate test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        tmate-server-host: 54.227.17.203
        tmate-server-port: 8080
        tmate-server-rsa-fingerprint: SHA256:jF4cetNQbVhft+ghrmG27mlhUEoAwhe5TPhjJHXhk28
        tmate-server-ed25519-fingerprint: SHA256:1Ks2ElkiTB09doDT6H2xbhsAGW+nHWU9gAwIot84md0
