name: Workflow Dispatch Tests (ssh-debug/tmate)

on: push

jobs:
  hello:
    runs-on: ["ubuntu-latest"]
    steps:
    - name: Print
      run: |
        ls -lah /usr/local/
        ls -lah /usr/local/bin/
