name: Tmate test

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Not on Monday or Wednesday
      run: | 
        env
        echo "----"
        cat /etc/environment
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: yanksyoon/action-tmate@feat/envvar
