name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  github-test:
    runs-on: [self-hosted]
    steps:
      - run: sudo apt-get update
      - run: time sudo docker pull jujusolutions/charm-base --quiet
