name: Workflow Dispatch Tests (ssh-debug/tmate)

on: push

jobs:
  hello:
    runs-on: ["self-hosted"]
    steps:
    - name: Print
      run: |
        echo Hello world!
        sleep 10
        echo "done"